### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by steve-hb** [E-Edu/e-edu.github.io-concept#13]
We should list all the currently active team members including skills

**Comment by TimyStream** [comment]
What do you mean directly with skills ?

**Comment by TimyStream** [comment]
And from Which Team ?

**Comment by steve-hb** [comment]
Our teams and the skills could be like:

Status: Head
Teams: TaskMS (Head), Gateway, Frontend
Skills: Development, Security, Infrastructure, Translation (Russian)
Languages: German, English, Russian

This way we can visualize who can do what is responsible for what

**Comment by TimyStream** [comment]
Already Done
