### ISSUE TITLE
Weird output in "Documentation"

### ISSUE THREAD

**Issue by steve-hb** [E-Edu/e-edu.github.io-concept#26]
When visiting the "Documentation" page I get this message in the middle of the screen:
`[comment]: <> (swagger direct link template : https://editor.swagger.io/?url=https://raw.githubusercontent.com/E-Edu/conept/master/documentation/dev/endpoints/swagger/)`

**Comment by RedstoneMedia** [comment]
I removed the message.
Change is in branch endpoints_documentation_wip.
