### ISSUE TITLE
Def Authorization and X-ServiceToken

### ISSUE THREAD

**Issue by n1xqe** [E-Edu/e-edu.github.io-concept#39]
## Microservice
report

## Priority
normal
Original Priority: 
> pls def Authorization and X-ServiceToken

## Issue
idk the format and the contend

**Comment by n1xqe** [comment]
Authorization or  X-ServiceToken definitely need role(int) and user_id

**Comment by adamane** [comment]
Authorization is the token that contains the User information. It is a JWT Token. X-ServiceToken is a bearer string that confirms the gateway to the MS

**Comment by iiestIT** [comment]
@adamane  ik. i need the specific content (specific names of the content)

**Comment by adamane** [comment]
We don't yet know what the JWT will contain, but the servicetoken is just a secret that's beeing shared

**Comment by n1xqe** [comment]
Ah ok

**Comment by n1xqe** [comment]
I take the things in the user doc

**Comment by steve-hb** [comment]
> Authorization is the token that contains the User information. It is a JWT Token. 

I would document as it is, except the "state" claim which would reveal whether a user is banned or not. What do u guys think?
