### ISSUE TITLE
New status format

### ISSUE THREAD

**Issue by n1xqe** [E-Edu/e-edu.github.io-concept#40]
## Microservice
report

## Priority
uniform response with the exception of /ticket/list (get)
format (example 200):
```
{
    "status": "OK",
    "code": 200,
    "timestamp": str:time,
    "path": str:path,
    "msg": str:msg
}
```

## Issue
There are more then one format for errors, etc..

**Comment by JavaDerg** [comment]
Please format the issues correctly and specify a valid Priority.

I'll take a look at the issue.

**Comment by JavaDerg** [comment]
Due too removal of the priority and moving the fcking actual issue into the priority???? and then making a tiny summory of the issue in the issue section I will be closing this issue till you fix your crap. WTF are you doing?

**Comment by JavaDerg** [comment]
Also we have a template that clearly tells you what to put there so use that PLEASE
