### ISSUE TITLE
missing value

### ISSUE THREAD

**Issue by n1xqe** [E-Edu/e-edu.github.io-concept#46]
## Microservice
report

## Priority
normal

## Issue
input (/ticket):
{
  "task_id": "string",
  "title": "string",
  "body": "string",
  "report_reason": "TROLLING"
}

output(/ticket/list):
[
  {
    "ticket_id": "string",
    "task_id": "string",
    "sender": "string",
    "title": "string",
    "body": "string",
    "ticket_type": "string"
  }
]

missing value "ticket_type" in the input (if "report_reason" = "ticket_type" pls select one name and fix it in the doc)
TROLLING is not a valid format

**Comment by adamane** [comment]
You are right, i will change it to report_reason

**Comment by adamane** [comment]
In the Swagger doc, you can switch between example and schema, and schema shoes the datatypes

**Comment by adamane** [comment]
Report_reason is a enum

**Comment by n1xqe** [comment]
ok
