### ISSUE TITLE
PubSub publish solutions

### ISSUE THREAD

**Issue by PAException** [E-Edu/e-edu.github.io-concept#50]
## Microservice

task

## Priority

high

## Issue

We implemented publish of freestyle and image solutions user sent.

### Freestyle

Path: `task.task.solution.freestyle.user`

Payload:

private int taskId
UUID authorId
UUID userId
String solution

### Image

Path: `task.task.solution.image.user`

Payload:

private int taskId
UUID authorId
UUID userId
String url

### User ban

user ban path is now btw `user.user.ban` view [Concept changes](https://github.com/E-Edu/concept/blob/master/changelog/meeting/20200420-conceptmeeting.md#6-pubsub)

**Comment by adamane** [comment]
I should rewrite the entire PubSub Documentation, and convert it to Markdown
