### ISSUE TITLE
change sender to user_id

### ISSUE THREAD

**Issue by n1xqe** [E-Edu/e-edu.github.io-concept#56]
## Microservice
report

## Priority
normal

## Issue
Endpoint: /ticket/list
Old:
[
  {
    "ticket_id": "string",
    "task_id": "string",
    "sender": "string",
    "title": "string",
    "body": "string",
    "ticket_type": "string"
  }
]
New:
[
  {
    "ticket_id": "string",
    "task_id": "string",
    "user_id": "string",
    "title": "string",
    "body": "string",
    "ticket_type": "string"
  }
]
change sender to user_id, because the input-data-name is also user_id

**Comment by adamane** [comment]
Done

**Comment by n1xqe** [comment]
pls do the same in report/support https://editor.swagger.io/?url=https://raw.githubusercontent.com/E-Edu/concept/endpoints_documentation_wip/documentation/dev/endpoints/swagger/report.yaml
