### ISSUE TITLE
Mobile Responsive 

### ISSUE THREAD

**Issue by NilocLP** [E-Edu/e-edu.github.io-concept#57]
## Microservice
{Add the microservice name here, which you have an issue in our documentation}

## Priority
{Describe the priority of your problem here}
Planned for Version 2.0
## Issue
{Describe the issue you have, with our endpoint documentation here}
Mobile Responsive for the complete Design

**Comment by adamane** [comment]
This is not an issue in relation to the Endpoint-Documentation, please rewrite without using our Template
