### ISSUE TITLE
Content Landing Page

### ISSUE THREAD

**Issue by NilocLP** [E-Edu/e-edu.github.io-concept#58]
## Microservice
{Add the microservice name here, which you have an issue in our documentation}
Design
## Priority
{Describe the priority of your problem here}
Fast
## Issue
{Describe the issue you have, with our endpoint documentation here}
The Landing page doesn't  contain content, so there isn't a good first impression. We need content to give the user a better impression and more information about the concept

**Comment by adamane** [comment]
Again, not in direct relation to the swagger docs we provide, please rewrite without using our Template
